// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AuthToken struct {
	Value string `json:"value"`
}

type ClientProfile struct {
	Name  *string `json:"name"`
	Login string  `json:"login"`
	Email *string `json:"email"`
}

type LoginInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type ResetTokenInput struct {
	ResetToken string `json:"resetToken"`
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleClient Role = "CLIENT"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleClient,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleClient:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
